/*
 * JSLEE Annotations
 * Copyright (c) 2015 Piotr Grabowski, All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:32:25 PM CET 
//


package jsleeannotations.xml.event;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jsleeannotations.xml.event package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jsleeannotations.xml.event
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LibraryVendor }
     * 
     */
    public LibraryVendor createLibraryVendor() {
        return new LibraryVendor();
    }

    /**
     * Create an instance of {@link EventTypeVersion }
     * 
     */
    public EventTypeVersion createEventTypeVersion() {
        return new EventTypeVersion();
    }

    /**
     * Create an instance of {@link EventJar }
     * 
     */
    public EventJar createEventJar() {
        return new EventJar();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link LibraryRef }
     * 
     */
    public LibraryRef createLibraryRef() {
        return new LibraryRef();
    }

    /**
     * Create an instance of {@link EventDefinition }
     * 
     */
    public EventDefinition createEventDefinition() {
        return new EventDefinition();
    }

    /**
     * Create an instance of {@link EventTypeVendor }
     * 
     */
    public EventTypeVendor createEventTypeVendor() {
        return new EventTypeVendor();
    }

    /**
     * Create an instance of {@link LibraryName }
     * 
     */
    public LibraryName createLibraryName() {
        return new LibraryName();
    }

    /**
     * Create an instance of {@link LibraryVersion }
     * 
     */
    public LibraryVersion createLibraryVersion() {
        return new LibraryVersion();
    }

    /**
     * Create an instance of {@link EventTypeName }
     * 
     */
    public EventTypeName createEventTypeName() {
        return new EventTypeName();
    }

    /**
     * Create an instance of {@link EventClassName }
     * 
     */
    public EventClassName createEventClassName() {
        return new EventClassName();
    }

}
