/*
 * JSLEE Annotations
 * Copyright (c) 2015 Piotr Grabowski, All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:24:46 PM CET 
//


package jsleeannotations.xml.sbb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "eventName",
    "eventTypeRef",
    "initialEventSelect",
    "initialEventSelectorMethodName",
    "eventResourceOption"
})
@XmlRootElement(name = "event")
public class Event {

    @XmlAttribute(name = "event-direction", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String eventDirection;
    @XmlAttribute(name = "initial-event")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String initialEvent;
    @XmlAttribute(name = "mask-on-attach")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maskOnAttach;
    @XmlAttribute(name = "last-in-transaction")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lastInTransaction;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected Description description;
    @XmlElement(name = "event-name", required = true)
    protected EventName eventName;
    @XmlElement(name = "event-type-ref", required = true)
    protected EventTypeRef eventTypeRef;
    @XmlElement(name = "initial-event-select")
    protected List<InitialEventSelect> initialEventSelect;
    @XmlElement(name = "initial-event-selector-method-name")
    protected InitialEventSelectorMethodName initialEventSelectorMethodName;
    @XmlElement(name = "event-resource-option")
    protected EventResourceOption eventResourceOption;

    /**
     * Gets the value of the eventDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventDirection() {
        return eventDirection;
    }

    /**
     * Sets the value of the eventDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventDirection(String value) {
        this.eventDirection = value;
    }

    /**
     * Gets the value of the initialEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialEvent() {
        if (initialEvent == null) {
            return "False";
        } else {
            return initialEvent;
        }
    }

    /**
     * Sets the value of the initialEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialEvent(String value) {
        this.initialEvent = value;
    }

    /**
     * Gets the value of the maskOnAttach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaskOnAttach() {
        if (maskOnAttach == null) {
            return "False";
        } else {
            return maskOnAttach;
        }
    }

    /**
     * Sets the value of the maskOnAttach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaskOnAttach(String value) {
        this.maskOnAttach = value;
    }

    /**
     * Gets the value of the lastInTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastInTransaction() {
        if (lastInTransaction == null) {
            return "True";
        } else {
            return lastInTransaction;
        }
    }

    /**
     * Sets the value of the lastInTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastInTransaction(String value) {
        this.lastInTransaction = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the eventName property.
     * 
     * @return
     *     possible object is
     *     {@link EventName }
     *     
     */
    public EventName getEventName() {
        return eventName;
    }

    /**
     * Sets the value of the eventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventName }
     *     
     */
    public void setEventName(EventName value) {
        this.eventName = value;
    }

    /**
     * Gets the value of the eventTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link EventTypeRef }
     *     
     */
    public EventTypeRef getEventTypeRef() {
        return eventTypeRef;
    }

    /**
     * Sets the value of the eventTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventTypeRef }
     *     
     */
    public void setEventTypeRef(EventTypeRef value) {
        this.eventTypeRef = value;
    }

    /**
     * Gets the value of the initialEventSelect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initialEventSelect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitialEventSelect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InitialEventSelect }
     * 
     * 
     */
    public List<InitialEventSelect> getInitialEventSelect() {
        if (initialEventSelect == null) {
            initialEventSelect = new ArrayList<InitialEventSelect>();
        }
        return this.initialEventSelect;
    }

    /**
     * Gets the value of the initialEventSelectorMethodName property.
     * 
     * @return
     *     possible object is
     *     {@link InitialEventSelectorMethodName }
     *     
     */
    public InitialEventSelectorMethodName getInitialEventSelectorMethodName() {
        return initialEventSelectorMethodName;
    }

    /**
     * Sets the value of the initialEventSelectorMethodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialEventSelectorMethodName }
     *     
     */
    public void setInitialEventSelectorMethodName(InitialEventSelectorMethodName value) {
        this.initialEventSelectorMethodName = value;
    }

    /**
     * Gets the value of the eventResourceOption property.
     * 
     * @return
     *     possible object is
     *     {@link EventResourceOption }
     *     
     */
    public EventResourceOption getEventResourceOption() {
        return eventResourceOption;
    }

    /**
     * Sets the value of the eventResourceOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventResourceOption }
     *     
     */
    public void setEventResourceOption(EventResourceOption value) {
        this.eventResourceOption = value;
    }

}
