/*
 * JSLEE Annotations
 * Copyright (c) 2015 Piotr Grabowski, All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:24:46 PM CET 
//


package jsleeannotations.xml.sbb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "sbbAbstractClass",
    "sbbLocalInterface",
    "sbbActivityContextInterface",
    "sbbUsageParametersInterface"
})
@XmlRootElement(name = "sbb-classes")
public class SbbClasses {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected Description description;
    @XmlElement(name = "sbb-abstract-class", required = true)
    protected SbbAbstractClass sbbAbstractClass;
    @XmlElement(name = "sbb-local-interface")
    protected SbbLocalInterface sbbLocalInterface;
    @XmlElement(name = "sbb-activity-context-interface")
    protected SbbActivityContextInterface sbbActivityContextInterface;
    @XmlElement(name = "sbb-usage-parameters-interface")
    protected SbbUsageParametersInterface sbbUsageParametersInterface;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the sbbAbstractClass property.
     * 
     * @return
     *     possible object is
     *     {@link SbbAbstractClass }
     *     
     */
    public SbbAbstractClass getSbbAbstractClass() {
        return sbbAbstractClass;
    }

    /**
     * Sets the value of the sbbAbstractClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link SbbAbstractClass }
     *     
     */
    public void setSbbAbstractClass(SbbAbstractClass value) {
        this.sbbAbstractClass = value;
    }

    /**
     * Gets the value of the sbbLocalInterface property.
     * 
     * @return
     *     possible object is
     *     {@link SbbLocalInterface }
     *     
     */
    public SbbLocalInterface getSbbLocalInterface() {
        return sbbLocalInterface;
    }

    /**
     * Sets the value of the sbbLocalInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link SbbLocalInterface }
     *     
     */
    public void setSbbLocalInterface(SbbLocalInterface value) {
        this.sbbLocalInterface = value;
    }

    /**
     * Gets the value of the sbbActivityContextInterface property.
     * 
     * @return
     *     possible object is
     *     {@link SbbActivityContextInterface }
     *     
     */
    public SbbActivityContextInterface getSbbActivityContextInterface() {
        return sbbActivityContextInterface;
    }

    /**
     * Sets the value of the sbbActivityContextInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link SbbActivityContextInterface }
     *     
     */
    public void setSbbActivityContextInterface(SbbActivityContextInterface value) {
        this.sbbActivityContextInterface = value;
    }

    /**
     * Gets the value of the sbbUsageParametersInterface property.
     * 
     * @return
     *     possible object is
     *     {@link SbbUsageParametersInterface }
     *     
     */
    public SbbUsageParametersInterface getSbbUsageParametersInterface() {
        return sbbUsageParametersInterface;
    }

    /**
     * Sets the value of the sbbUsageParametersInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link SbbUsageParametersInterface }
     *     
     */
    public void setSbbUsageParametersInterface(SbbUsageParametersInterface value) {
        this.sbbUsageParametersInterface = value;
    }

}
